services:
  # Simple Crawler Worker - Recommended for reliable deployment
  - type: worker
    name: simple-wordpress-crawler
    env: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python simple_wp_crawler.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    disk:
      name: simple-crawler-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1

  # Web Service - For monitoring and results download
  - type: web
    name: wordpress-crawler-web
    env: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn render_crawler:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    disk:
      name: crawler-web-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1

  # Unified Crawler Alternative (defaults to simple mode)
  - type: worker
    name: unified-crawler
    env: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python start_crawlers.py
    envVars:
      - key: CRAWLER_MODE
        value: simple
      - key: PYTHONUNBUFFERED
        value: "1"
    disk:
      name: unified-crawler-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
